// src/users/user.repository.ts
// Pure data-access layer. Only Prisma calls — zero business logic.

import {
  User,
  Organization,
  PasswordResetToken,
  OrganizationType,
  UserRole,
} from "../../generated/client";
import { SafeUser, SafeOrg } from "./user.types";

import prisma from "../../config/prisma";

// ─── Projections ──────────────────────────────────────────────────────────────

export function toSafeUser(user: User): SafeUser {
  return {
    id:             user.id,
    name:           user.name,
    email:          user.email,
    role:           user.role,
    organizationId: user.organizationId,
    createdAt:      user.createdAt,
  };
}

export function toSafeOrg(org: Organization): SafeOrg {
  return {
    id:        org.id,
    name:      org.name,
    email:     org.email,
    type:      org.type,
    createdAt: org.createdAt,
  };
}

// ─── User queries ─────────────────────────────────────────────────────────────

export async function findUserByEmail(email: string): Promise<User | null> {
  return prisma.user.findUnique({
    where: { email: email.toLowerCase().trim() },
  });
}

export async function findUserById(id: string): Promise<User | null> {
  return prisma.user.findUnique({ where: { id } });
}

// ─── Organisation queries ─────────────────────────────────────────────────────

export async function findOrgById(id: string): Promise<Organization | null> {
  return prisma.organization.findUnique({ where: { id } });
}

export async function findOrgByEmail(email: string): Promise<Organization | null> {
  return prisma.organization.findUnique({
    where: { email: email.toLowerCase().trim() },
  });
}

export async function findOrgByInviteCode(code: string): Promise<Organization | null> {
  return prisma.organization.findUnique({ where: { inviteCode: code } });
}

// ─── Registration — Individual ────────────────────────────────────────────────
// Creates a personal INDIVIDUAL org + OWNER user atomically.

export async function createIndividualWithOrg(data: {
  userName:     string;
  email:        string;
  passwordHash: string;
}): Promise<{ user: User; org: Organization }> {
  return prisma.$transaction(async (tx) => {
    // The org email mirrors the user email for an individual account
    const org = await tx.organization.create({
      data: {
        name:  data.userName,          // org name = user's name for individuals
        email: data.email.toLowerCase().trim(),
        type:  "INDIVIDUAL" as OrganizationType,
        inviteCode: null,              // no invite code for individual orgs
      },
    });

    const user = await tx.user.create({
      data: {
        name:           data.userName,
        email:          data.email.toLowerCase().trim(),
        password:       data.passwordHash,
        role:           "OWNER" as UserRole,
        organizationId: org.id,
      },
    });

    return { user, org };
  });
}

// ─── Registration — Create Organisation ──────────────────────────────────────
// Creates an ORGANIZATION org + ADMIN user atomically.

export async function createOrgWithAdmin(data: {
  userName:     string;
  email:        string;
  passwordHash: string;
  orgName:      string;
  inviteCode:   string;   // generated by service layer
}): Promise<{ user: User; org: Organization }> {
  return prisma.$transaction(async (tx) => {
    const org = await tx.organization.create({
      data: {
        name:       data.orgName,
        email:      data.email.toLowerCase().trim(),
        type:       "ORGANIZATION" as OrganizationType,
        inviteCode: data.inviteCode,
      },
    });

    const user = await tx.user.create({
      data: {
        name:           data.userName,
        email:          data.email.toLowerCase().trim(),
        password:       data.passwordHash,
        role:           "ADMIN" as UserRole,
        organizationId: org.id,
      },
    });

    return { user, org };
  });
}

// ─── Registration — Join Organisation ────────────────────────────────────────
// Creates a MEMBER user linked to an existing org.

export async function createMemberInOrg(data: {
  userName:       string;
  email:          string;
  passwordHash:   string;
  organizationId: string;
}): Promise<User> {
  return prisma.user.create({
    data: {
      name:           data.userName,
      email:          data.email.toLowerCase().trim(),
      password:       data.passwordHash,
      role:           "MEMBER" as UserRole,
      organizationId: data.organizationId,
    },
  });
}

// ─── Password Reset ───────────────────────────────────────────────────────────

export async function createPasswordResetToken(data: {
  userId:         string;
  organizationId: string;
  token:          string;
  expiresAt:      Date;
}): Promise<PasswordResetToken> {
  // Invalidate any live tokens for this user before issuing a new one
  await prisma.passwordResetToken.updateMany({
    where: { userId: data.userId, usedAt: null },
    data:  { usedAt: new Date() },
  });

  return prisma.passwordResetToken.create({ data });
}

export async function findValidResetToken(token: string): Promise<PasswordResetToken | null> {
  return prisma.passwordResetToken.findFirst({
    where: {
      token,
      usedAt:    null,
      expiresAt: { gt: new Date() },
    },
  });
}

export async function markResetTokenUsed(tokenId: string): Promise<void> {
  await prisma.passwordResetToken.update({
    where: { id: tokenId },
    data:  { usedAt: new Date() },
  });
}

export async function updateUserPassword(userId: string, passwordHash: string): Promise<void> {
  await prisma.user.update({
    where: { id: userId },
    data:  { password: passwordHash },
  });
}